/**
 * Carga de rosters REALES 2026 de los 32 equipos UCI WorldTour ya
 * cargados por import-uci-data.ts. Fuente: Wikipedia ("List of 2026
 * UCI WorldTeams and riders" y páginas individuales de equipo),
 * cyclingnews.com, sitios oficiales de equipo (fdj-suez.fr) y notas de
 * prensa de equipo, consultado 2026-09-11. Cada ciclista fue
 * verificado en una página real — ninguno es inventado.
 *
 * Nota de calidad de datos: Justyna Czapla (Canyon//SRAM) figura como
 * nacionalidad "Alemania" en procyclingstats pese a haber nacido en
 * Ruda Śląska, Polonia — confirmado correcto (compite por Alemania),
 * no es un error de carga.
 *
 * Requiere que los equipos (Team) ya existan — correr después de
 * import-uci-data.ts. Idempotente (upsert por slug).
 */
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

function slugify(name: string): string {
  return name
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

interface RosterEntry {
  team: string
  riders: [string, string][] // [nombre, país]
}

const ROSTERS: RosterEntry[] = [
  { team: 'alpecin-premier-tech', riders: [['Maurice Ballerstedt', 'Alemania'], ['Tobias Bayer', 'Austria'], ['Lennert Belmans', 'Bélgica'], ['Francesco Busatto', 'Italia'], ['Lindsay De Vylder', 'Bélgica'], ['Ramses Debruyne', 'Bélgica'], ['Simon Dehairs', 'Bélgica'], ['Tibor Del Grosso', 'Países Bajos'], ['Silvan Dillier', 'Suiza'], ['Aaron Dockx', 'Bélgica'], ['Jonas Geens', 'Bélgica'], ['Gal Glivar', 'Eslovenia'], ['Michael Gogl', 'Austria'], ['Kaden Groves', 'Australia'], ['Hugo Houle', 'Canadá'], ['Tim Marsman', 'Países Bajos'], ['Jasper Philipsen', 'Bélgica'], ['Edward Planckaert', 'Bélgica'], ['Jensen Plowright', 'Australia'], ['Johan Price-Pejtersen', 'Dinamarca'], ['Senna Remijn', 'Países Bajos'], ['Jonas Rickaert', 'Bélgica'], ['Oscar Riesebeek', 'Países Bajos'], ['Florian Sénéchal', 'Francia'], ['Sente Sentjens', 'Bélgica'], ['Gerben Thijssen', 'Bélgica'], ['Henri Uhlig', 'Alemania'], ['Mathieu van der Poel', 'Países Bajos'], ['Luca Vergallito', 'Italia'], ['Emiel Verstrynge', 'Bélgica']] },
  { team: 'decathlon-cma-cgm', riders: [['Tobias Lund Andresen', 'Dinamarca'], ['Tiesj Benoot', 'Bélgica'], ['Léo Bisiaux', 'Francia'], ['Stefan Bissegger', 'Suiza'], ['Cees Bol', 'Países Bajos'], ['Oscar Chamberlain', 'Australia'], ['Sander De Pestel', 'Bélgica'], ['Stan Dewulf', 'Bélgica'], ['Felix Gall', 'Austria'], ['Pierre Gautherat', 'Francia'], ['Robbe Ghys', 'Bélgica'], ['Tord Gudmestad', 'Noruega'], ['Daan Hoole', 'Países Bajos'], ['Noa Isidore', 'Francia'], ['Olav Kooij', 'Países Bajos'], ['Jordan Labrosse', 'Francia'], ['Paul Lapeira', 'Francia'], ["Antoine L'Hote", 'Francia'], ['Gregor Mühlberger', 'Austria'], ['Oliver Naesen', 'Bélgica'], ['Aurélien Paret-Peintre', 'Francia'], ['Rasmus Søjberg Pedersen', 'Dinamarca'], ['Gianluca Pollefliet', 'Bélgica'], ['Nicolas Prodhomme', 'Francia'], ['Matthew Riccitello', 'Estados Unidos'], ['Callum Scotson', 'Australia'], ['Paul Seixas', 'Francia'], ['Johannes Staune-Mittet', 'Noruega']] },
  { team: 'ef-education-easypost', riders: [['Mattia Agostinacchio', 'Italia'], ['Vincenzo Albanese', 'Italia'], ['Kasper Asgreen', 'Dinamarca'], ['Samuele Battistella', 'Italia'], ['Alex Baudin', 'Francia'], ['Markel Beloki', 'España'], ['Richard Carapaz', 'Ecuador'], ['Jefferson Alexander Cepeda', 'Ecuador'], ['Ben Healy', 'Irlanda'], ['Noah Hobbs', 'Reino Unido'], ['Mikkel Frølich Honoré', 'Dinamarca'], ['Luke Lamperti', 'Estados Unidos'], ['Michael Leonard', 'Canadá'], ['Alastair Mackellar', 'Australia'], ['Madis Mihkels', 'Estonia'], ['Lukas Nerurkar', 'Reino Unido'], ['Neilson Powless', 'Estados Unidos'], ['Sean Quinn', 'Estados Unidos'], ['Darren Rafferty', 'Irlanda'], ['Juan Felipe Rodríguez', 'Colombia'], ['Archie Ryan', 'Irlanda'], ['Matthias Schwarzbacher', 'Eslovaquia'], ['James Shaw', 'Reino Unido'], ['Colby Simmons', 'Estados Unidos'], ['Georg Steinhauser', 'Alemania'], ['Harry Sweeny', 'Australia'], ['Michael Valgren', 'Dinamarca'], ['Marijn van den Berg', 'Países Bajos'], ['Jardi van der Lee', 'Países Bajos'], ['Max Walker', 'Reino Unido']] },
  { team: 'groupama-fdj-united', riders: [['Cyril Barthe', 'Francia'], ['Clément Berthet', 'Francia'], ['Lewis Bower', 'Nueva Zelanda'], ['Clément Braz Afonso', 'Francia'], ['Rémi Cavagna', 'Francia'], ['Ewen Costiou', 'Francia'], ['Maxime Decomble', 'Francia'], ['Tom Donnenwirth', 'Francia'], ['Titouan Fontaine', 'Francia'], ['David Gaudu', 'Francia'], ['Kévin Geniets', 'Luxemburgo'], ['Lorenzo Germani', 'Italia'], ['Romain Grégoire', 'Francia'], ['Thibaud Gruel', 'Francia'], ['Axel Huens', 'Francia'], ['Johan Jacobs', 'Suiza'], ['Josh Kench', 'Nueva Zelanda'], ['Olivier Le Gac', 'Francia'], ['Valentin Madouas', 'Francia'], ['Guillaume Martin', 'Francia'], ['Matteo Milan', 'Italia'], ['Rudy Molard', 'Francia'], ['Quentin Pacher', 'Francia'], ['Enzo Paleni', 'Francia'], ['Paul Penhoët', 'Francia'], ['Rémy Rochas', 'Francia'], ['Brieuc Rolland', 'Francia'], ['Clément Russo', 'Francia'], ['Bastien Tronchon', 'Francia']] },
  { team: 'lidl-trek', riders: [['Juan Ayuso', 'España'], ['Andrea Bagioli', 'Italia'], ['Julien Bernard', 'Francia'], ['Giulio Ciccone', 'Italia'], ['Simone Consonni', 'Italia'], ['Tao Geoghegan Hart', 'Reino Unido'], ['Amanuel Ghebreigzabhier', 'Eritrea'], ['Lennard Kämna', 'Alemania'], ['Patrick Konrad', 'Austria'], ['Søren Kragh Andersen', 'Dinamarca'], ['Jonathan Milan', 'Italia'], ['Bauke Mollema', 'Países Bajos'], ['Jacopo Mosca', 'Italia'], ['Mathias Norsgaard', 'Dinamarca'], ['Thibau Nys', 'Bélgica'], ['Sam Oomen', 'Países Bajos'], ['Mads Pedersen', 'Dinamarca'], ['Albert Withen Philipsen', 'Dinamarca'], ['Quinn Simmons', 'Estados Unidos'], ['Mattias Skjelmose', 'Dinamarca'], ['Toms Skujiņš', 'Letonia'], ['Matteo Sobrero', 'Italia'], ['Jakob Söderqvist', 'Suecia'], ['Tim Torn Teutenberg', 'Alemania'], ['Edward Theuns', 'Bélgica'], ['Mathias Vacek', 'República Checa'], ['Otto Vergaerde', 'Bélgica'], ['Carlos Verona', 'España'], ['Max Walscheid', 'Alemania']] },
  { team: 'lotto-intermarche', riders: [['Toon Aerts', 'Bélgica'], ['Huub Artz', 'Países Bajos'], ['Jenno Berckmoes', 'Bélgica'], ['Cédric Beullens', 'Bélgica'], ['Vito Braet', 'Bélgica'], ['Lars Craps', 'Bélgica'], ['Jasper De Buyst', 'Bélgica'], ['Arnaud De Lie', 'Bélgica'], ['Steffen De Schuyteneer', 'Bélgica'], ['Matthew Fox', 'Australia'], ['Joshua Giddings', 'Reino Unido'], ['Sébastien Grignard', 'Bélgica'], ['Matys Grisel', 'Francia'], ['Simone Gualdi', 'Italia'], ['Mathieu Kockelmann', 'Luxemburgo'], ['Milan Menten', 'Bélgica'], ['Robin Orins', 'Bélgica'], ['Lorenzo Rota', 'Italia'], ['Jonas Rutsch', 'Alemania'], ['Liam Slock', 'Bélgica'], ['Lionel Taminiaux', 'Bélgica'], ['Reuben Thompson', 'Nueva Zelanda'], ['Luca Van Boven', 'Bélgica'], ['Taco van der Hoorn', 'Países Bajos'], ['Lennert Van Eetvelt', 'Bélgica'], ['Roel van Sintmaartensdijk', 'Países Bajos'], ['Baptiste Veistroffer', 'Francia'], ['Jarno Widar', 'Bélgica'], ['Georg Zimmermann', 'Alemania'], ['Felix Ørn-Kristoff', 'Noruega']] },
  { team: 'movistar-team', riders: [['Roger Adrià', 'España'], ['Jorge Arcas', 'España'], ['Orluis Aular', 'Venezuela'], ['Jon Barrenetxea', 'España'], ['Carlos Canal', 'España'], ['Pablo Castrillo', 'España'], ['Jefferson Alveiro Cepeda', 'Ecuador'], ['Davide Formolo', 'Italia'], ['Iván García Cortina', 'España'], ['Raúl García Pierna', 'España'], ['Michel Hessmann', 'Alemania'], ['Juan Pedro López', 'España'], ['Enric Mas', 'España'], ['Lorenzo Milesi', 'Italia'], ['Manlio Moro', 'Italia'], ['Pavel Novák', 'República Checa'], ['Nelson Oliveira', 'Portugal'], ['Diego Pescador', 'Colombia'], ['Nairo Quintana', 'Colombia'], ['Iván Romeo', 'España'], ['Javier Romo', 'España'], ['Einer Rubio', 'Colombia'], ['Pelayo Sánchez', 'España'], ['Gonzalo Serrano', 'España'], ['Natnael Tesfatsion', 'Eritrea'], ['Albert Torres', 'España'], ['Cian Uijtdebroeks', 'Bélgica']] },
  { team: 'netcompany-ineos', riders: [['Thymen Arensman', 'Países Bajos'], ['Andrew August', 'Estados Unidos'], ['Egan Bernal', 'Colombia'], ['Laurens De Plus', 'Bélgica'], ['Tobias Foss', 'Noruega'], ['Filippo Ganna', 'Italia'], ['Dorian Godon', 'Francia'], ['Jack Haig', 'Australia'], ['Lucas Hamilton', 'Australia'], ['Kim Heiduk', 'Alemania'], ['Bob Jungels', 'Luxemburgo'], ['Michał Kwiatkowski', 'Polonia'], ['Victor Langellotti', 'Mónaco'], ['Axel Laurance', 'Francia'], ['Oscar Onley', 'Reino Unido'], ['Brandon Rivera', 'Colombia'], ['Carlos Rodríguez', 'España'], ['Óscar Rodríguez', 'España'], ['Magnus Sheffield', 'Estados Unidos'], ['Artem Shmidt', 'Estados Unidos'], ['Embret Svestad-Bårdseng', 'Noruega'], ['Ben Swift', 'Reino Unido'], ['Connor Swift', 'Reino Unido'], ['Joshua Tarling', 'Reino Unido'], ['Ben Turner', 'Reino Unido'], ['Kévin Vauquelin', 'Francia'], ['Samuel Watson', 'Reino Unido'], ['Sam Welsford', 'Australia'], ['Peter Øxenberg', 'Dinamarca']] },
  { team: 'nsn-cycling-team', riders: [['Lewis Askey', 'Reino Unido'], ['George Bennett', 'Nueva Zelanda'], ['Joseph Blackmore', 'Reino Unido'], ['Guillaume Boivin', 'Canadá'], ['Simon Clarke', 'Australia'], ['Pier-André Côté', 'Canadá'], ['Itamar Einhorn', 'Israel'], ['Marco Frigo', 'Italia'], ['Brady Gilmore', 'Australia'], ['Biniam Girmay', 'Eritrea'], ['Jan Hirt', 'República Checa'], ['Hugo Hofstetter', 'Francia'], ['Oded Kogut', 'Israel'], ['Matis Louvel', 'Francia'], ['Alexey Lutsenko', 'Kazajistán'], ['Pau Martí', 'España'], ['Ryan Mullen', 'Irlanda'], ['Krists Neilands', 'Letonia'], ['Alessandro Pinarello', 'Italia'], ['Nadav Raisberg', 'Israel'], ['Nick Schultz', 'Australia'], ['Riley Sheehan', 'Estados Unidos'], ['Jake Stewart', 'Reino Unido'], ['Corbin Strong', 'Nueva Zelanda'], ['Tom Van Asbroeck', 'Bélgica'], ['Floris Van Tricht', 'Bélgica'], ['Ethan Vernon', 'Reino Unido'], ['Stephen Williams', 'Reino Unido']] },
  { team: 'red-bull-bora-hansgrohe', riders: [['Giovanni Aleotti', 'Italia'], ['Adrien Boichis', 'Francia'], ['Mattia Cattaneo', 'Italia'], ['Nico Denz', 'Alemania'], ['Jarrad Drizners', 'Australia'], ['Haimar Etxeberria', 'España'], ['Remco Evenepoel', 'Bélgica'], ['Finn Fisher-Black', 'Nueva Zelanda'], ['Alexander Hajek', 'Austria'], ['Emil Herzog', 'Alemania'], ['Jai Hindley', 'Australia'], ['Florian Lipowitz', 'Alemania'], ['Arne Marit', 'Bélgica'], ['Daniel Martínez', 'Colombia'], ['Jordi Meeus', 'Bélgica'], ['Gianni Moscon', 'Italia'], ['Giulio Pellizzari', 'Italia'], ['Laurence Pithie', 'Nueva Zelanda'], ['Primož Roglič', 'Eslovenia'], ['Callum Thornley', 'Reino Unido'], ['Jan Tratnik', 'Eslovenia'], ['Luke Tuckwell', 'Australia'], ['Mick van Dijke', 'Países Bajos'], ['Tim van Dijke', 'Países Bajos'], ['Maxim Van Gils', 'Bélgica'], ['Danny van Poppel', 'Países Bajos'], ['Gianni Vermeersch', 'Bélgica'], ['Aleksandr Vlasov', 'Rusia'], ['Frederik Wandahl', 'Dinamarca'], ['Ben Zwiehoff', 'Alemania']] },
  { team: 'soudal-quick-step', riders: [['Ayco Bastiaens', 'Bélgica'], ['Steff Cras', 'Bélgica'], ['Alberto Dainese', 'Italia'], ['Pascal Eenkhoorn', 'Países Bajos'], ['Gianmarco Garofoli', 'Italia'], ['Gil Gelders', 'Bélgica'], ['Ethan Hayter', 'Reino Unido'], ['Yves Lampaert', 'Bélgica'], ['Mikel Landa', 'España'], ['Junior Lecerf', 'Bélgica'], ['Paul Magnier', 'Francia'], ['Tim Merlier', 'Bélgica'], ['Valentin Paret-Peintre', 'Francia'], ['Casper Pedersen', 'Dinamarca'], ['Pepijn Reinderink', 'Países Bajos'], ['Laurenz Rex', 'Bélgica'], ['Maximilian Schachmann', 'Alemania'], ['Jasper Stuyven', 'Bélgica'], ['Martin Svrček', 'Eslovaquia'], ['Dylan van Baarle', 'Países Bajos'], ['Fabio Van den Bossche', 'Bélgica'], ['Dries Van Gestel', 'Bélgica'], ['Bert Van Lerberghe', 'Bélgica'], ['Ilan Van Wilder', 'Bélgica'], ['Warre Vangheluwe', 'Bélgica'], ['Mauri Vansevenant', 'Bélgica'], ['Louis Vervaeke', 'Bélgica'], ['Filippo Zana', 'Italia']] },
  { team: 'team-bahrain-victorious', riders: [['Nikias Arndt', 'Alemania'], ['Phil Bauhaus', 'Alemania'], ['Pello Bilbao', 'España'], ['Alessandro Borgo', 'Italia'], ['Alberto Bruttomesso', 'Italia'], ['Santiago Buitrago', 'Colombia'], ['Damiano Caruso', 'Italia'], ['Roman Ermakov', 'Rusia'], ['Žak Eržen', 'Eslovenia'], ['Afonso Eulálio', 'Portugal'], ['Matevž Govekar', 'Eslovenia'], ['Kamil Gradek', 'Polonia'], ['Rainer Kepplinger', 'Austria'], ['Lenny Martinez', 'Francia'], ['Fran Miholjević', 'Croacia'], ['Pau Miquel', 'España'], ['Matej Mohorič', 'Eslovenia'], ['Jakob Omrzel', 'Eslovenia'], ['Mathijs Paasschens', 'Países Bajos'], ['Alec Segaert', 'Bélgica'], ['Daniel Skerl', 'Italia'], ['Robert Stannard', 'Australia'], ['Oliver Stockwell', 'Reino Unido'], ['Antonio Tiberi', 'Italia'], ['Attila Valter', 'Hungría'], ['Max van der Meulen', 'Países Bajos'], ['Vlad Van Mechelen', 'Bélgica'], ['Edoardo Zambanini', 'Italia']] },
  { team: 'team-jayco-alula', riders: [['Pascal Ackermann', 'Alemania'], ['Koen Bouwman', 'Países Bajos'], ['Amaury Capiot', 'Bélgica'], ['Filippo Conca', 'Italia'], ['Alessandro Covi', 'Italia'], ['Dries De Bondt', 'Bélgica'], ['Dries De Pooter', 'Bélgica'], ['Davide De Pretto', 'Italia'], ['Bob Donaldson', 'Reino Unido'], ['Paul Double', 'Reino Unido'], ['Luke Durbridge', 'Australia'], ['Felix Engelhardt', 'Alemania'], ['Anders Foldager', 'Dinamarca'], ['Patrick Gamper', 'Austria'], ['Alan Hatherly', 'Sudáfrica'], ['Asbjørn Hellemose', 'Dinamarca'], ['Christopher Juul-Jensen', 'Dinamarca'], ['Jelte Krijnsen', 'Países Bajos'], ['Michael Matthews', 'Australia'], ['Hamish McKenzie', 'Australia'], ['Luka Mezgec', 'Eslovenia'], ["Kelland O'Brien", 'Australia'], ["Ben O'Connor", 'Australia'], ['Finlay Pickering', 'Reino Unido'], ['Luke Plapp', 'Australia'], ['Rudy Porter', 'Australia'], ['Mauro Schmid', 'Suiza'], ['Jasha Sütterlin', 'Alemania'], ['Andrea Vendrame', 'Italia']] },
  { team: 'team-picnic-postnl', riders: [['Warren Barguil', 'Francia'], ['Pavel Bittner', 'República Checa'], ['Dillon Corkery', 'Irlanda'], ['John Degenkolb', 'Alemania'], ['Robbe Dhondt', 'Bélgica'], ['Matthew Dinham', 'Australia'], ['Nils Eekhoff', 'Países Bajos'], ['Alexy Faure Prost', 'Francia'], ['Sean Flynn', 'Reino Unido'], ['Mattia Gaffuri', 'Italia'], ['Chris Hamilton', 'Australia'], ['Fabio Jakobsen', 'Países Bajos'], ['Timo de Jong', 'Países Bajos'], ['James Knox', 'Reino Unido'], ['Gijs Leemreize', 'Países Bajos'], ['Enzo Leijnse', 'Países Bajos'], ['Niklas Märkl', 'Alemania'], ['Tim Naberman', 'Países Bajos'], ['Max Poole', 'Reino Unido'], ['Timo Roosen', 'Países Bajos'], ['Julius van den Berg', 'Países Bajos'], ['Frank van den Broek', 'Países Bajos'], ['Casper van Uden', 'Países Bajos'], ['Bram Welten', 'Países Bajos']] },
  { team: 'visma-lease-a-bike', riders: [['Edoardo Affini', 'Italia'], ['Bruno Armirail', 'Francia'], ['Louis Barré', 'Francia'], ['Niklas Behrens', 'Alemania'], ['Matthew Brennan', 'Reino Unido'], ['Victor Campenaerts', 'Bélgica'], ['Owain Doull', 'Reino Unido'], ['Filippo Fiorelli', 'Italia'], ['Tijmen Graat', 'Países Bajos'], ['Per Strand Hagenes', 'Noruega'], ['Menno Huising', 'Países Bajos'], ['Matteo Jorgenson', 'Estados Unidos'], ['Wilco Kelderman', 'Países Bajos'], ['Timo Kielich', 'Bélgica'], ['Steven Kruijswijk', 'Países Bajos'], ['Sepp Kuss', 'Estados Unidos'], ['Christophe Laporte', 'Francia'], ['Bart Lemmen', 'Países Bajos'], ['Jørgen Nordhagen', 'Noruega'], ['Pietro Mattio', 'Italia'], ['Davide Piganzoli', 'Italia'], ['Tim Rex', 'Bélgica'], ['Anton Schiffer', 'Alemania'], ['Ben Tulett', 'Reino Unido'], ['Wout van Aert', 'Bélgica'], ['Loe van Belle', 'Países Bajos'], ['Jonas Vingegaard', 'Dinamarca'], ['Axel Zingle', 'Francia']] },
  { team: 'uae-team-emirates-xrg', riders: [['João Almeida', 'Portugal'], ['Igor Arrieta', 'España'], ['Filippo Baroncini', 'Italia'], ['Mikkel Bjerg', 'Dinamarca'], ['Jan Christen', 'Suiza'], ['Benoît Cosnefroy', 'Francia'], ['Isaac del Toro', 'México'], ['Luca Giaimi', 'Italia'], ['Felix Großschartner', 'Austria'], ['Rune Herregodts', 'Bélgica'], ['Julius Johansen', 'Dinamarca'], ['Vegard Stake Laengen', 'Noruega'], ['Brandon McNulty', 'Estados Unidos'], ['Juan Sebastián Molano', 'Colombia'], ['António Morgado', 'Portugal'], ['Jhonatan Narváez', 'Ecuador'], ['Domen Novak', 'Eslovenia'], ['Ivo Oliveira', 'Portugal'], ['Rui Oliveira', 'Portugal'], ['Adrià Pericas', 'España'], ['Tadej Pogačar', 'Eslovenia'], ['Nils Politt', 'Alemania'], ['Pavel Sivakov', 'Francia'], ['Marc Soler', 'España'], ['Pablo Torres', 'España'], ['Kevin Vermaerke', 'Estados Unidos'], ['Florian Vermeersch', 'Bélgica'], ['Jay Vine', 'Australia'], ['Tim Wellens', 'Bélgica'], ['Adam Yates', 'Reino Unido']] },
  { team: 'uno-x-mobility', riders: [['Jonas Abrahamsen', 'Noruega'], ['Erlend Blikra', 'Noruega'], ['Martin Urianstad Bugge', 'Noruega'], ['Fredrik Dversnes', 'Noruega'], ['Stian Fredheim', 'Noruega'], ['Markus Hoelgaard', 'Noruega'], ['Ådne Holter', 'Noruega'], ['Jonas Iversby Hvideberg', 'Noruega'], ['Storm Ingebrigtsen', 'Noruega'], ['Anders Halland Johannessen', 'Noruega'], ['Tobias Halland Johannessen', 'Noruega'], ['Andreas Leknessund', 'Noruega'], ['Sakarias Koller Løland', 'Noruega'], ['Erik Resell', 'Noruega'], ['Anders Skaarseth', 'Noruega'], ['Rasmus Tiller', 'Noruega'], ['Martin Tjøtta', 'Noruega'], ['Søren Wærenskjold', 'Noruega'], ['Sven Erik Bystrøm', 'Noruega'], ['Torstein Træen', 'Noruega'], ['Carl-Frederik Bévort', 'Dinamarca'], ['William Blume Levy', 'Dinamarca'], ['Magnus Cort', 'Dinamarca'], ['Simon Dalby', 'Dinamarca'], ['Anthon Charmig', 'Dinamarca'], ['Andreas Kron', 'Dinamarca'], ['Johannes Kulset', 'Dinamarca'], ['Alexander Kamp', 'Dinamarca'], ['Henrik Pedersen', 'Dinamarca'], ['Tobias Svarre', 'Dinamarca']] },
  { team: 'xds-astana-team', riders: [['Davide Ballerini', 'Italia'], ['Alberto Bettiol', 'Italia'], ['Clément Champoussin', 'Francia'], ['Nicola Conci', 'Italia'], ['Yevgeniy Fedorov', 'Kazajistán'], ['Lorenzo Fortunato', 'Italia'], ['Aaron Gate', 'Nueva Zelanda'], ['Lev Gonov', 'Rusia'], ['Sergio Higuita', 'Colombia'], ['Florian Samuel Kajamini', 'Italia'], ['Max Kanter', 'Alemania'], ['Anton Kuzmin', 'Kazajistán'], ['Arjen Livyns', 'Bélgica'], ['Harold Martín López', 'Ecuador'], ['Matteo Malucelli', 'Italia'], ['Henok Mulubrhan', 'Eritrea'], ['Cristián Rodríguez', 'España'], ['Alessandro Romele', 'Italia'], ['Christian Scaroni', 'Italia'], ['Marco Schrettl', 'Austria'], ['Thomas Silva', 'Uruguay'], ['Su Haoyu', 'China'], ['Gleb Syritsa', 'Rusia'], ['Harold Tejada', 'Colombia'], ['Mike Teunissen', 'Países Bajos'], ['Davide Toneatti', 'Italia'], ['Diego Ulissi', 'Italia'], ['Darren van Bekkum', 'Países Bajos'], ['Simone Velasco', 'Italia'], ['Nicolas Vinokurov', 'Kazajistán']] },
  { team: 'ag-insurance-soudal', riders: [['Fauve Bastiaenssen', 'Bélgica'], ['Letizia Borghesi', 'Italia'], ['Shari Bossuyt', 'Bélgica'], ['Alana Castrique', 'Bélgica'], ['Kim Le Court-Pienaar', 'Mauricio'], ['Justine Ghekiere', 'Bélgica'], ['Sarah Gigante', 'Australia'], ['Marthe Goossens', 'Bélgica'], ['Anya Louw', 'Australia'], ['Alexandra Manly', 'Australia'], ['Ashleigh Moolman Pasio', 'Sudáfrica'], ['Mireia Benito Pellicer', 'España'], ['Ilse Pluimers', 'Países Bajos'], ['Lore De Schepper', 'Bélgica'], ['Julie Van de Velde', 'Bélgica'], ['Gladys Verhulst-Wild', 'Francia'], ['Urška Žigart', 'Eslovenia']] },
  { team: 'canyon-sram', riders: [['Katarzyna Niewiadoma-Phinney', 'Polonia'], ['Cecilie Uttrup Ludwig', 'Dinamarca'], ['Zoë Bäckstedt', 'Reino Unido'], ['Wilma Aintila', 'Finlandia'], ['Neve Bradbury', 'Australia'], ['Chiara Consonni', 'Italia'], ['Tiffany Cromwell', 'Australia'], ['Justyna Czapla', 'Alemania'], ['Chloé Dygert', 'Estados Unidos'], ['Rosa Maria Klöser', 'Alemania'], ['Anastasiya Kolesava', 'Bielorrusia'], ['Maria Martins', 'Portugal'], ['Antonia Niedermaier', 'Alemania'], ['Soraya Paladin', 'Italia'], ['Agnieszka Skalniak-Sojka', 'Polonia'], ['Maike van der Duin', 'Países Bajos']] },
  { team: 'ef-education-oatly', riders: [['Minke Solbjørk Anderson', 'Dinamarca'], ['Nina Berton', 'Luxemburgo'], ['Auke De Buysser', 'Bélgica'], ['Kim Cadzow', 'Nueva Zelanda'], ['Henrietta Christie', 'Nueva Zelanda'], ['Axelle Dubau-Prévot', 'Francia'], ['Kristen Faulkner', 'Estados Unidos'], ['Stina Kagevi', 'Suecia'], ['Cédrine Kerbaol', 'Francia'], ['Mirre Knaven', 'Países Bajos'], ['Alexis Magner', 'Estados Unidos'], ['Magdeleine Vallières', 'Canadá'], ["Caoimhe O'Brien", 'Irlanda'], ['Noemi Rüegg', 'Suiza'], ['Alice Towers', 'Reino Unido'], ['Alexandra Volstad', 'Canadá'], ['Babette van der Wolf', 'Países Bajos']] },
  { team: 'fdj-united-suez', riders: [['Sofia Bertizzolo', 'Italia'], ['Juliette Berthet', 'Francia'], ['Elise Chabbey', 'Suiza'], ['Kate Courtney', 'Estados Unidos'], ['Léa Curinier', 'Francia'], ['Lauren Dickson', 'Reino Unido'], ['Célia Géry', 'Francia'], ['Vittoria Guazzini', 'Italia'], ['Franziska Koch', 'Alemania'], ['Amber Kraak', 'Países Bajos'], ['Marie Le Net', 'Francia'], ['Evita Muzic', 'Francia'], ['Eglantine Rayer', 'Francia'], ['Eva van Agt', 'Países Bajos'], ['Demi Vollering', 'Países Bajos'], ['Jade Wiel', 'Francia'], ['Ally Wollaston', 'Nueva Zelanda']] },
  { team: 'fenix-premier-tech', riders: [['Puck Pieterse', 'Países Bajos'], ['Charlotte Kool', 'Países Bajos'], ['Ceylin del Carmen Alvarado', 'Países Bajos'], ['Sara Casasola', 'Italia'], ['Lotte Claes', 'Bélgica'], ['Millie Couzens', 'Reino Unido'], ['Julie De Wilde', 'Bélgica'], ['Flora Perkins', 'Reino Unido'], ['Yara Kastelijn', 'Países Bajos'], ['Evy Kuijpers', 'Países Bajos'], ['Carina Schrempf', 'Austria'], ['Christina Schweinberger', 'Austria'], ['Marthe Truyen', 'Bélgica'], ['Aniek van Alphen', 'Países Bajos'], ['Inge van der Heijden', 'Países Bajos'], ['Mylene de Zoete', 'Países Bajos'], ['Xaydée Van Sinaey', 'Bélgica'], ['Fien Van Eynde', 'Bélgica']] },
  { team: 'human-powered-health', riders: [['Yurani Blanco', 'España'], ['Giada Borghesi', 'Italia'], ['Nina Buijsman', 'Países Bajos'], ['Carlotta Cipressi', 'Italia'], ['Maggie Coles-Lyster', 'Canadá'], ['Jente Koops', 'Países Bajos'], ['Thalita de Jong', 'Países Bajos'], ['Ruth Edwards', 'Estados Unidos'], ['Marta Jaskulska', 'Polonia'], ['Barbara Malcotti', 'Italia'], ['Mona Mitterwallner', 'Austria'], ['Daria Pikulik', 'Polonia'], ['Wiktoria Pikulik', 'Polonia'], ['Marit Raaijmakers', 'Países Bajos'], ['Katia Ragusa', 'Italia'], ['Titia Ryo', 'Francia'], ['Kathrin Schweinberger', 'Austria'], ['Petra Stiasny', 'Suiza'], ['Lily Williams', 'Estados Unidos'], ['Silvia Zanardi', 'Italia']] },
  { team: 'lidl-trek-women', riders: [['Loes Adegeest', 'Países Bajos'], ['Shirin van Anrooij', 'Países Bajos'], ['Elisa Balsamo', 'Italia'], ['Ricarda Bauernfeind', 'Alemania'], ['Lucinda Brand', 'Países Bajos'], ['Clara Copponi', 'Francia'], ['Niamh Fisher-Black', 'Nueva Zelanda'], ['Lauretta Hanson', 'Australia'], ['Anna Henderson', 'Reino Unido'], ['Ava Holmgren', 'Canadá'], ['Isabella Holmgren', 'Canadá'], ['Marine Lenehan', 'Irlanda'], ['Riejanne Markus', 'Países Bajos'], ['Fleur Moors', 'Bélgica'], ['Emma Norsgaard', 'Dinamarca'], ['Gaia Realini', 'Italia'], ['Amanda Spratt', 'Australia'], ['Margot Vanpachtenbeke', 'Bélgica'], ['Felicity Wilson-Haffenden', 'Australia']] },
  { team: 'liv-alula-jayco', riders: [['Caroline Andersson', 'Suecia'], ['Georgia Baker', 'Australia'], ['Monica Trinca Colonel', 'Italia'], ['Mackenzie Coupland', 'Australia'], ['Nadia Gontova', 'Canadá'], ['Noa Jansen', 'Países Bajos'], ['Jeanne Korevaar', 'Países Bajos'], ['Amber Pate', 'Australia'], ['Letizia Paternoster', 'Italia'], ['Ruby Roseman-Gannon', 'Australia'], ['Silke Smulders', 'Países Bajos'], ['Josie Talbot', 'Australia'], ['Quinty Ton', 'Países Bajos'], ['Matilde Vitillo', 'Italia'], ['Ella Wyllie', 'Nueva Zelanda']] },
  { team: 'movistar-team-women', riders: [['Marlen Reusser', 'Suiza'], ['Liane Lippert', 'Alemania'], ['Aude Biannic', 'Francia'], ['Olivia Baril', 'Canadá'], ['Francesca Barale', 'Italia'], ['Sheyla Gutiérrez', 'España'], ['Cat Ferguson', 'Reino Unido'], ['Floortje Mackaij', 'Países Bajos'], ['Ana Magalhães', 'Brasil'], ['Sara Martín', 'España'], ['Mareille Meijering', 'Países Bajos'], ['Carys Lloyd', 'Reino Unido'], ['Laura Ruiz', 'España'], ['Lucía Ruiz', 'España'], ['Arlenis Sierra', 'Cuba'], ['Claire Steels', 'Reino Unido'], ['Paula Ostiz', 'España']] },
  { team: 'team-picnic-postnl-women', riders: [['Megan Arens', 'Países Bajos'], ['Rachele Barbieri', 'Italia'], ['Eleonora Ciabocco', 'Italia'], ['Robyn Clay', 'Reino Unido'], ['Lucie Fityus', 'Australia'], ['Pfeiffer Georgi', 'Reino Unido'], ['Mia Griffin', 'Irlanda'], ['Daniela Hezinová', 'República Checa'], ['Ella Heremans', 'Bélgica'], ['Audrey De Keersmaeker', 'Bélgica'], ['Juliana Londoño', 'Colombia'], ['Gaia Masetti', 'Italia'], ['Dilyxine Miermont', 'Francia'], ['Josie Nelson', 'Reino Unido'], ['Mara Roldan', 'Canadá'], ['Becky Storrie', 'Reino Unido'], ['Elise Uijen', 'Países Bajos']] },
  { team: 'team-sd-worx-protime', riders: [['Mischa Bredewold', 'Países Bajos'], ['Valentina Cavallar', 'Austria'], ['Elena Cecchini', 'Italia'], ['Femke Gerritse', 'Países Bajos'], ['Barbara Guarischi', 'Italia'], ['Steffi Häberlin', 'Suiza'], ['Mikayla Harvey', 'Nueva Zelanda'], ['Julia Kopecký', 'República Checa'], ['Lotte Kopecky', 'Bélgica'], ['Marta Lach', 'Polonia'], ['Femke Markus', 'Países Bajos'], ['Marie Schreiber', 'Luxemburgo'], ['Lisa van Belle', 'Países Bajos'], ['Anna van der Breggen', 'Países Bajos'], ['Blanka Vas', 'Hungría'], ['Nienke Vinke', 'Países Bajos'], ['Lorena Wiebes', 'Países Bajos']] },
  { team: 'uae-team-limad', riders: [['Alena Amialiusik', 'Bielorrusia'], ['Paula Blasi', 'España'], ['Elisa Longo Borghini', 'Italia'], ['Elynor Bäckstedt', 'Reino Unido'], ['Brodie Chapman', 'Australia'], ['Febe Jooris', 'Bélgica'], ['Mavi García', 'España'], ['Eleonora Gasparrini', 'Italia'], ['Lara Gillespie', 'Irlanda'], ['Alena Ivanchenko', 'Rusia'], ['Megan Jastrab', 'Estados Unidos'], ['Erica Magnaldi', 'Italia'], ['Greta Marturano', 'Italia'], ['Silvia Persico', 'Italia'], ['Pauliena Rooijakkers', 'Países Bajos'], ['Sofie van Rooijen', 'Países Bajos'], ['Safia Al-Sayegh', 'EAU'], ['Maëva Squiban', 'Francia'], ['Karlijn Swinkels', 'Países Bajos'], ['Federica Venturelli', 'Italia'], ['Dominika Włodarczyk', 'Polonia']] },
  { team: 'uno-x-mobility-women', riders: [['Katrine Aalerud', 'Noruega'], ['Kamilla Aasebø', 'Noruega'], ['Anniina Ahtosalo', 'Finlandia'], ['Susanne Andersen', 'Noruega'], ['Elinor Barker', 'Reino Unido'], ['Teuntje Beekhuis', 'Países Bajos'], ['Marte Berg Edseth', 'Noruega'], ['Jelena Erić', 'Serbia'], ['Mia Gjertsen', 'Noruega'], ['Alberte Greve', 'Dinamarca'], ['Ingvild Gåskjenn', 'Noruega'], ['Sigrid Ytterhus Haugset', 'Noruega'], ['Rebecca Koerner', 'Dinamarca'], ['Anouska Koster', 'Países Bajos'], ['Mie Bjørndal Ottestad', 'Noruega'], ['Francesca Pellegrini', 'Italia'], ['Laura Tomasi', 'Italia'], ['Alessia Vigilia', 'Italia'], ['Anne Dorthe Ysland', 'Noruega'], ['Linda Zanetti', 'Suiza']] },
  { team: 'visma-lease-a-bike-women', riders: [['Marion Bunel', 'Francia'], ['Viktória Chladoňová', 'Eslovaquia'], ['Sarah van Dam', 'Canadá'], ['Fem van Empel', 'Países Bajos'], ['Pauline Ferrand-Prévot', 'Francia'], ['Martina Fidanza', 'Italia'], ['Daniek Hengeveld', 'Países Bajos'], ['Lieke Nooijen', 'Países Bajos'], ['Maud Oudeman', 'Países Bajos'], ['Rosita Reijnhout', 'Países Bajos'], ['Katharina Sadnik', 'Austria'], ['Nienke Veenhoven', 'Países Bajos'], ['Margaux Vigié', 'Francia'], ['Marianne Vos', 'Países Bajos'], ['Femke de Vries', 'Países Bajos'], ['Imogen Wolff', 'Reino Unido']] },
]

async function main() {
  let riderCount = 0
  let skippedTeams = 0

  for (const { team: teamSlug, riders } of ROSTERS) {
    const team = await prisma.team.findUnique({ where: { slug: teamSlug } })
    if (!team) {
      console.warn(`⚠️  Equipo no encontrado, se omite: ${teamSlug}`)
      skippedTeams++
      continue
    }

    for (const [name, nationality] of riders) {
      const slug = slugify(name)
      await prisma.rider.upsert({
        where: { slug },
        update: { name, nationality, currentTeamId: team.id },
        create: { slug, name, nationality, currentTeamId: team.id },
      })
      riderCount++
    }
  }

  console.log(`✅ ${riderCount} ciclistas reales cargados (temporada 2026).`)
  if (skippedTeams > 0) console.warn(`⚠️  ${skippedTeams} equipos no encontrados en la BD.`)
  console.log('🎉 Importación de rosters UCI completada.')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
